# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |vm1|
    vm1.vm.box  = "centos/7"
#   config.vm.network "forwarded_port", guest: 8080, host: 8080
    vm1.vm.network "public_network", ip: "192.168.12.210"

end 

  config.vm.define "vm1" do |vm2|
    config.vm.box = "centos/7"
#   config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "public_network", ip: "192.168.12.211"

end

# Run the Bash script during provisioning
config.vm.provision "shell", path: "exec.sh"

end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 2
    vb.memory = "4096"

end


# Vagrant.configure("2") do |config|
#   config.vm.box = "centos/7"
#   config.vm.network "forwarded_port", guest: 8080, host: 8080
# # config.vm.network "private_network", type: "dhcp"
# # config.vm.network "forwarded_port", guest: 8080, host: 8080, id: "Web"
#   config.vm.provider "virtualbox" do |vb|
#     vb.memory = "1024"
#     vb.cpus = 2
#   end
# end
