## Vagrant File

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "vm1" do |vm1|
        vm1.vm.box = "centos/7"
        vm1.vm.network "public_network", ip: "192.168.12.210"
    end

    config.vm.define "vm2" do |vm2|
        vm2.vm.box = "centos/7"
        vm2.vm.network "public_network", ip: "192.168.12.211"
    end

    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = "2048"
    end

    config.vm.provision "shell", inline: <<-SHELL
      sudo yum -y update
      sudo yum -y install httpd
    SHELL
end

